# Generated by Django 6.0.1 on 2026-02-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0005_ingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="dishes", to="kitchen.ingredient"
            ),
        ),
    ]
