# Generated by Django 6.0.1 on 2026-02-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0006_dish_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
