# Generated by Django 6.0.1 on 2026-02-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0007_alter_ingredient_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True, related_name="dishes", to="kitchen.ingredient"
            ),
        ),
    ]
