# Generated by Django 6.0.1 on 2026-02-11 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0008_alter_dish_ingredients"),
    ]

    operations = [
        migrations.CreateModel(
            name="DishIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("g", "g"),
                            ("ml", "ml"),
                            ("pcs", "pcs"),
                            ("tsp", "tsp"),
                            ("tbsp", "tbsp"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kitchen.dish"
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kitchen.ingredient",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dish", "ingredient"), name="unique_dish_ingredient"
                    )
                ],
            },
        ),
    ]
