# Generated by Django 6.0.1 on 2026-02-11 18:39

from django.db import migrations


def forwards(apps, schema_editor):
    Dish = apps.get_model("kitchen", "Dish")
    DishIngredient = apps.get_model("kitchen", "DishIngredient")

    old_through = Dish.ingredients.through  # старий auto M2M table

    objs = []
    for row in old_through.objects.all():
        # row має поля dish_id і ingredient_id
        objs.append(DishIngredient(dish_id=row.dish_id, ingredient_id=row.ingredient_id))

    DishIngredient.objects.bulk_create(objs, ignore_conflicts=True)

def backwards(apps, schema_editor):
    DishIngredient = apps.get_model("kitchen", "DishIngredient")
    DishIngredient.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0009_dishingredient"),  # Django підставить автоматом, перевір тільки
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
