# Generated by Django 6.0.1 on 2026-02-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0009_dishingredient"),
        ("kitchen", "0010_copy_ingredients_m2m_to_through"),
    ]

    operations = []
