# Generated by Django 6.0.1 on 2026-02-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0009_dishingredient"),
        ("kitchen", "0010_copy_ingredients_m2m_to_through"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="ingredients",
        ),
        migrations.AddField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                to="kitchen.ingredient",
                through="kitchen.DishIngredient",
                related_name="dishes",
                blank=True,
            ),
        ),
    ]
