# Generated by Django 6.0.1 on 2026-02-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0011_merge_20260211_2048"),
        ("kitchen", "0012_switch_ingredients_to_through"),
    ]

    operations = []
