# Generated by Django 6.0.1 on 2026-02-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0013_merge_20260211_2100"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
